version: "3"
services:
  # redis:
  #   image: redis
  db:
    image: postgres
    volumes: # Persist the data!
      - "/tmp/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myapp_user
      POSTGRES_DB: myapp_db
    ports:
      - "15432:5432"
  web:
    image: node:8-alpine
    command: "node /app/server/index.js"
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - "db"
    ports:
      - "3010:3010"
    links:
      - "db"
      # - "redis"
    environment:
      DB_PASSWORD: password
      DB_USER: myapp_user
      DB_NAME: myapp_db
      DB_HOST: db
      # REDIS_HOST: redis